// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSgRM26T0qAEb9VTANC6p2CLv11n4FPB4',
    appId: '1:754231422578:web:89629ff957f01519329ceb',
    messagingSenderId: '754231422578',
    projectId: 'paywise-11111',
    authDomain: 'paywise-11111.firebaseapp.com',
    storageBucket: 'paywise-11111.appspot.com',
    measurementId: 'G-FRGMYWXBS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvnpRmAa12c8Qj1hfZpG6wGAW1FQre9IM',
    appId: '1:754231422578:android:301efdd5db40e6aa329ceb',
    messagingSenderId: '754231422578',
    projectId: 'paywise-11111',
    storageBucket: 'paywise-11111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAikJnxCS2FGg4nJOtuVH2Am1fAfljdfc8',
    appId: '1:754231422578:ios:a4c56b1b12831ea5329ceb',
    messagingSenderId: '754231422578',
    projectId: 'paywise-11111',
    storageBucket: 'paywise-11111.appspot.com',
    androidClientId: '754231422578-8s6igautah7ed4qk442f5afjagtn3b1n.apps.googleusercontent.com',
    iosClientId: '754231422578-h2u97to9p9kfbk2tjdcbspv38u83pfje.apps.googleusercontent.com',
    iosBundleId: 'com.example.paywise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAikJnxCS2FGg4nJOtuVH2Am1fAfljdfc8',
    appId: '1:754231422578:ios:a4c56b1b12831ea5329ceb',
    messagingSenderId: '754231422578',
    projectId: 'paywise-11111',
    storageBucket: 'paywise-11111.appspot.com',
    androidClientId: '754231422578-8s6igautah7ed4qk442f5afjagtn3b1n.apps.googleusercontent.com',
    iosClientId: '754231422578-h2u97to9p9kfbk2tjdcbspv38u83pfje.apps.googleusercontent.com',
    iosBundleId: 'com.example.paywise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSgRM26T0qAEb9VTANC6p2CLv11n4FPB4',
    appId: '1:754231422578:web:882ff453ffc2a10d329ceb',
    messagingSenderId: '754231422578',
    projectId: 'paywise-11111',
    authDomain: 'paywise-11111.firebaseapp.com',
    storageBucket: 'paywise-11111.appspot.com',
    measurementId: 'G-D6VT5Z9LB3',
  );

}